CREATE TABLE IF NOT EXISTS auth (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	phone varchar(20) NOT NULL,
	organization varchar(32) NOT NULL,
	code integer NOT NULL,
	request_time bigint NOT NULL,
	typeOfSign integer)

CREATE TABLE IF NOT EXISTS usersa0eebc999c0b4ef8bb6d6bb9bd380a11 (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(40) NOT NULL,
	phone varchar(20)NOT NULL,
	password varchar(255) NOT NULL) 
	
CREATE TABLE IF NOT EXISTS requestsignin (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	phone varchar(20) NOT NULL,
	organization varchar(32) NOT NULL,
	code integer NOT NULL,
	request_time big int NOT NULL)


DROP TABLE IF EXISTS usersa0eebc999c0b4ef8bb6d6bb9bd380a11

SELECT * FROM usersa0eebc999c0b4ef8bb6d6bb9bd380a11